package com.packt.webstore.models;


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Ja on 27.05.2017.
 */
// Imports ...

@Entity
@Table(name = "Product")
public class Product {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    @NotNull
    private String name;
    @NotNull
    private long unitPrice;
    @NotNull
    private String manufacturer;
    @NotNull
    private String category;
    private long unitsInStock;
    private long unitsInOrder;
    private boolean discontinued;
    private String condition;


    // Public methods

    public Product() { }

    public Product(long id) {
        this.id = id;
    }

    public Product(String email, String name) {
        this.name = name;
    }

    // Getter and setter methods
    // ...

}
